#!/bin/bash
# add home-developed library to site-packages
python -c "import shutil; shutil.copytree(src='/home/jovyan/libs/evaluation', dst='/srv/conda/envs/notebook/lib/python3.8/site-packages/evaluation', dirs_exist_ok=True,)"
